-- Stores quote estimates generated by visitors using the Get Quote tool
CREATE TABLE IF NOT EXISTS public.quotes (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  structure text,
  structure_price_label text,
  sector text,
  addons jsonb DEFAULT '[]'::jsonb,
  usd_total integer DEFAULT 0,
  tzs_total bigint DEFAULT 0,
  created_at timestamptz DEFAULT now()
);

ALTER TABLE public.quotes ENABLE ROW LEVEL SECURITY;

-- Anyone can insert a quote (anonymous lead capture)
CREATE POLICY "Anyone can insert quotes"
  ON public.quotes FOR INSERT
  WITH CHECK (true);

-- Only admins can read quotes
CREATE POLICY "Admins can read quotes"
  ON public.quotes FOR SELECT
  USING (public.has_role('admin', auth.uid()));
