// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vignkvsicocvqzlovsfw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZpZ25rdnNpY29jdnF6bG92c2Z3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwODk0MTUsImV4cCI6MjA2NjY2NTQxNX0.3M5lnNW7wqEig6qjxO6uVPbyn3Wr1c65VADia9s6Z7Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);